### ISSUE TITLE
Python3 support is broken

### ISSUE THREAD

**Issue by danni-m** [RedisLabs/RAMP#31]
```
# ramp
Traceback (most recent call last):
  File "/usr/local/bin/ramp", line 6, in <module>
    from RAMP.ramp import ramp
  File "/usr/local/lib/python3.5/dist-packages/RAMP/ramp.py", line 7, in <module>
    from RAMP.packer import package
  File "/usr/local/lib/python3.5/dist-packages/RAMP/packer.py", line 102
    print output.format(**metadata)
               ^
SyntaxError: invalid syntax
```

**Comment by MPalarya** [comment]
this seems to be fixed by Rafi on July 30
